runtime: python311
entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

env_variables:
  GEMINI_API_KEY: "AIzaSyDBqXU6t6kQWPZrIm-niaQA-TnoAPAtXA8"
  TENANT_API_URL: "https://demo.api.lahis.ohtk.org"
  LAHIS_CLIENT_ID: "your_client_id_here"
  LAHIS_CLIENT_SECRET: "your_client_secret_here"
  LAHIS_LANG: "lo"
